version: '3'
services:
  cloudflared:
    image: cloudflare/cloudflared:2022.3.4-amd64
    user: root
    command: tunnel
    environment:
      - TUNNEL_HOSTNAME=camera.yude.jp
      - TUNNEL_URL=http://192.168.100.80:8086/0/stream
      - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
    volumes:
      - '$HOME/.cloudflared:/root/.cloudflared'
    restart: always
