version: '2'

services:
  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
    restart: unless-stopped
    volumes:
      - ./db/sqlite:/var/roundcube/db
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://yudejp.sakura.ne.jp
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://yudejp.sakura.ne.jp
  
  cloudflared:
    image: cloudflare/cloudflared:2022.3.4-amd64
    user: root
    command: tunnel
    environment:
      - TUNNEL_HOSTNAME=roundcube.yude.jp
      - TUNNEL_URL=http://roundcubemail:80
      - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
    volumes:
      - '$HOME/.cloudflared:/root/.cloudflared'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
