version: "3"

services:
  web:
    image: misskey/misskey:12.119.0
    restart: always
    links:
      - db
      - redis
    volumes:
      - ./files:/misskey/files
      - ./.config/default.yml:/misskey/.config/default.yml:ro

  redis:
    restart: always
    image: redis:4.0-alpine
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:12.2-alpine
    env_file:
      - .config/docker.env
    volumes:
      - socks:/var/run
      - ./db:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: misskey
    volumes:
      - ./nginx/misskey.conf:/etc/nginx/conf.d/misskey.conf
    restart: always

#  cron-backup:
#    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile.crontab
#    volumes:
#      - socks:/var/run
#      - type: bind
#        source: ./backup
#        target: /app/backup
#      - type: bind
#        source: /megasync-admin-yude-jp/misskey.yude.jp
#        target: /app/compressed
#      - type: bind
#        source: ./.config
#        target: /app/.config
#      - type: bind
#        source: ./redis
#        target: /app/redis
#      - type: bind
#        source: ./files
#        target: /app/files

volumes:
  socks:
