version: "3"

services:
  web:
#    build: https://github.com/misskey-dev/misskey.git#12.103.1
    image: misskey/misskey:12.109.2
    restart: always
    links:
      - db
      - redis
    volumes:
      - ./files:/misskey/files
      - ./.config/default.yml:/misskey/.config/default.yml:ro

  redis:
    restart: always
    image: redis:4.0-alpine
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:12.2-alpine
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: misskey
    volumes:
      - ./nginx/misskey.conf:/etc/nginx/conf.d/misskey.conf
    restart: always
