epg:
  cache-dir: /var/lib/mirakc/epg

server:
  addrs:
    - !http '0.0.0.0:40772'
    - !unix /var/run/mirakc.sock

channels:
  # Add channels of interest.
  - name: 'ＮＨＫＥテレ１広島'
    type: 'GR'
    channel: '13'

  - name: 'ＮＨＫ総合１・広島'
    type: 'GR'
    channel: '14'

  - name: 'ＮＨＫＥテレ１広島'
    type: 'GR'
    channel: '15'

  - name: 'ＲＣＣテレビ１'
    type: 'GR'
    channel: '16'

  - name: '広島テレビ１'
    type: 'GR'
    channel: '17'

  - name: 'ＲＣＣテレビ１'
    type: 'GR'
    channel: '18'

  - name: '広島テレビ１'
    type: 'GR'
    channel: '19'

  - name: 'ＮＨＫ総合１・広島'
    type: 'GR'
    channel: '21'

  - name: '広島ホームテレビ１'
    type: 'GR'
    channel: '20'

  - name: 'テレビ新広島１'
    type: 'GR'
    channel: '23'

  - name: 'テレビ新広島１'
    type: 'GR'
    channel: '27'

  - name: 'グリーンチャンネル'
    type: 'BS'
    channel: 'BS21_2'
    services: [234]

  - name: 'スターチャンネル１'
    type: 'BS'
    channel: 'BS09_1'
    services: [201]

  - name: 'スターチャンネル２'
    type: 'BS'
    channel: 'BS15_1'
    services: [202]

  - name: 'スターチャンネル３'
    type: 'BS'
    channel: 'BS15_1'
    services: [211]

  - name: 'ディズニーｃｈ'
    type: 'BS'
    channel: 'BS23_0'
    services: [256]

  - name: '放送大学ｅｘ'
    type: 'BS'
    channel: 'BS11_1'
    services: [231]

  - name: '放送大学ｏｎ'
    type: 'BS'
    channel: 'BS11_1'
    services: [232]

  - name: '日本映画専門ｃｈ'
    type: 'BS'
    channel: 'BS21_1'
    services: [255]

  - name: 'ＢＳよしもと'
    type: 'BS'
    channel: 'BS23_1'
    services: [265]

  - name: 'ＢＳアニマックス'
    type: 'BS'
    channel: 'BS13_2'
    services: [236]

  - name: 'ＢＳスカパー！'
    type: 'BS'
    channel: 'BS11_0'
    services: [241]

  - name: 'ＢＳテレ東'
    type: 'BS'
    channel: 'BS01_2'
    services: [171]

  - name: 'ＢＳフジ・１８１'
    type: 'BS'
    channel: 'BS13_1'
    services: [181]

  - name: 'ＢＳフジ・１８２'
    type: 'BS'
    channel: 'BS13_1'
    services: [182]

  - name: 'ＢＳ日テレ'
    type: 'BS'
    channel: 'BS13_0'
    services: [141]

  - name: 'ＢＳ朝日１'
    type: 'BS'
    channel: 'BS01_0'
    services: [151]

  - name: 'ＢＳ松竹東急'
    type: 'BS'
    channel: 'BS23_3'
    services: [260]

  - name: 'ＢＳ釣りビジョン'
    type: 'BS'
    channel: 'BS11_2'
    services: [251]

  - name: 'ＢＳ－ＴＢＳ'
    type: 'BS'
    channel: 'BS01_1'
    services: [161]

  - name: 'ＢＳ１１イレブン'
    type: 'BS'
    channel: 'BS09_0'
    services: [211]

  - name: 'ＢＳ１２トゥエルビ'
    type: 'BS'
    channel: 'BS09_2'
    services: [222]

  - name: 'ＢＳＪａｐａｎｅｘｔ'
    type: 'BS'
    channel: 'BS23_2'
    services: [263]

  - name: 'Ｊ　ＳＰＯＲＴＳ　１'
    type: 'BS'
    channel: 'BS19_0'
    services: [245]

  - name: 'Ｊ　ＳＰＯＲＴＳ　２'
    type: 'BS'
    channel: 'BS19_1'
    services: [242]

  - name: 'Ｊ　ＳＰＯＲＴＳ　３'
    type: 'BS'
    channel: 'BS19_2'
    services: [243]

  - name: 'Ｊ　ＳＰＯＲＴＳ　４'
    type: 'BS'
    channel: 'BS19_3'
    services: [244]

  - name: 'ＮＨＫＢＳプレミアム'
    type: 'BS'
    channel: 'BS03_1'
    services: [103]

  - name: 'ＮＨＫＢＳ１'
    type: 'BS'
    channel: 'BS15_0'
    services: [101]

  - name: 'ＷＯＷＯＷシネマ'
    type: 'BS'
    channel: 'BS05_1'
    services: [193]

  - name: 'ＷＯＷＯＷプライム'
    type: 'BS'
    channel: 'BS03_0'
    services: [191]

  - name: 'ＷＯＷＯＷライブ'
    type: 'BS'
    channel: 'BS05_0'
    services: [192]

  # - name: 'テレ朝チャンネル１'
  #   type: 'CS'
  #   channel: ''
  #   services: []

  # - name: 'テレ朝チャンネル２'
  #   type: 'CS'
  #   channel: ''
  #   services: []

  # - name: '東映チャンネル'
  #   type: 'CS'
  #   channel: ''
  #   services: []

tuners:
  # Add tuners available on a local machine.
  - name: sat1
    types: [BS, CS]
    command: >-
      recpt1 --device /dev/px4video0 {{{channel}}} - -
  - name: sat2
    types: [BS, CS]
    command: >-
      recpt1 --device /dev/px4video1 {{{channel}}} - -
  - name: gr1
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video2 {{{channel}}} - -
  - name: gr2
    types: [GR]
    command: >-
      recpt1 --device /dev/px4video3 {{{channel}}} - -

filters:
  decode-filter:
    command: >-
      arib-b25-stream-test
