
version: '3.9'
services:
  haste-server:
    image: ghcr.io/yude/haste-server:master
    container_name: hastebin
    environment:
      - STORAGE_TYPE=file
      - STORAGE_FILEPATH=/data
      - KEYGENERATOR_TYPE=random
    volumes:
      - type: bind
        source: /mnt/data3/haste-server-data
        target: /data
      - type: bind
        source: ./README.md
        target: /data/about.md
    restart: always