global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: 'yudejp-monitor'

# rule_files:
#   - /etc/prometheus/alert.rules

# alerting:
#   alertmanagers:
#     - scheme: http
#       static_configs:
#         - targets:
#           - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
        - prometheus:9090
  - file_sd_configs:
    - files:
      - /etc/prometheus/node.yaml
    job_name: node