version: '3.8'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/grafana
    expose:
      - 3000
    user: '1000'
    networks:
      - grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-image-renderer
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: https://grafana.yude.jp/
      GF_LOG_FILTERS: rendering:debug
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: unless-stopped
    command: tunnel --url http://grafana:3000 --no-chunked-encoding run grafana
    volumes:
      - '$HOME/.cloudflared:/root/.cloudflared'
    networks:
      - grafana

  renderer:
    image: grafana/grafana-image-renderer:latest
    networks:
      - grafana

networks:
  grafana: