version: '3.8'

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/grafana
    expose:
      - 3000
    user: '1000'
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource,grafana-image-renderer
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: https://grafana.yude.jp/
      GF_LOG_FILTERS: rendering:debug
    depends_on:
      - renderer

  renderer:
    image: grafana/grafana-image-renderer:latest
