version: '3'

services:
  db:
    image: postgres:13.5-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - db.env
    networks:
      - internal

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal

  app:
    image: nextcloud:fpm
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./data/html:/var/www/html
      - /mnt/data1:/storage/data1
      - /mnt/data2:/storage/data2
      - /mnt/data3:/storage/data3
      - /mnt/data4:/storage/data4
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - internal
      - default
    command: bash -c "
        apt -y update && apt -y upgrade &&
        apt -y install libmagickcore-6.q16-6-extra
        && php-fpm
      "
  
  web:
    image: nginx
    restart: always
    links:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
    volumes_from:
      - app
    depends_on:
      - app
    networks:
      - internal
      - default

  cloudflared:
    image: cloudflare/cloudflared:2021.8.3
    user: root
    command: tunnel
    environment:
      - TUNNEL_HOSTNAME=nc.yude.jp
      - TUNNEL_URL=http://web:80
      - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
    volumes:
      - '$HOME/.cloudflared:/root/.cloudflared'
    networks:
      - internal
    restart: always

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./data/html:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - internal

networks:
  internal:
