version: '3'
services:
  app:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.yude.jp'
    volumes:
      - './data/config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'
      - '/mnt/data2/gitlab-data:/var/opt/gitlab'

  cloudflared:
    image: cloudflare/cloudflared:2022.4.0-amd64
    user: root
    command: tunnel
    environment:
      - TUNNEL_HOSTNAME=gitlab.yude.jp
      - TUNNEL_URL=http://app:8080
      - TUNNEL_ORIGIN_CERT=/root/.cloudflared/cert.pem
    volumes:
      - '$HOME/.cloudflared:/root/.cloudflared'
    restart: always
    depends_on:
      - app
