version: '3.9'
services:
  h2o:
    image: lkwg82/h2o-http2-server:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: "./h2o.conf"
        target: "/etc/h2o/h2o.conf"
      - type: bind
        source: "./html"
        target: "/var/www/html"
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: unless-stopped
    command: tunnel --url http://h2o:8080 --no-chunked-encoding run fakku
    volumes:
      - '$HOME/.cloudflared:/root/.cloudflared'
