version: '3.3'

services:
  app:
    build: https://github.com/iamtakagi/ShadowbanAlerts-Docker.git
    container_name: shadowban-alerts
    volumes:
      - type: bind
        source: './crontab'
        target: '/app/crontab'
      - type: bind
        source: './ShadowbanAlerts.json'
        target: '/app/ShadowbanAlerts.json'
    env_file:
          - .env
    restart: unless-stopped
