version: '3.9'
services:
  h2o:
    image: lkwg82/h2o-http2-server:latest
    container_name: hiroshima
    hostname: hiroshima
    restart: unless-stopped
    volumes:
      - type: bind
        source: "./h2o.conf"
        target: "/etc/h2o/h2o.conf"
      - type: bind
        source: "./html"
        target: "/var/www/html"
