version: '3'
services:
    mirakc:
        container_name: mirakc
        image: yude/mirakc:latest
        cap_add:
            - SYS_ADMIN
            - SYS_NICE
        ports:
            - "40772:40772"
            - "9229:9229"
        volumes:
            - ./mirakc/epg:/var/lib/mirakc/epg
            - ./mirakc/config.yml:/etc/mirakc/config.yml
            - socks:/var/run
        devices:
            - /dev/isdb6014video0:/dev/isdb6014video0
            - /dev/isdb6014video1:/dev/isdb6014video1
            - /dev/isdb6014video2:/dev/isdb6014video2
            - /dev/isdb6014video3:/dev/isdb6014video3
            - /dev/bus:/dev/bus
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"
        user: 0:0
        environment:
            TZ: Asia/Tokyo
            RUST_LOG: info,mirakc=debug
            RUST_BACKTRACE: full

    mysql:
        container_name: mysql-epgstation
        image: mariadb:10.4
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_USER: epgstation
            MYSQL_PASSWORD: epgstation
            MYSQL_ROOT_PASSWORD: epgstation
            MYSQL_DATABASE: epgstation
            TZ: "Asia/Tokyo"
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --performance-schema=false --expire_logs_days=1
        restart: always
        logging:
            options:
                max-size: "10m"
                max-file: "3"

    epgstation:
        container_name: epgstation
        image: collelog/epgstation:latest-alpine-vaapi-amd64
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./epgstation/config:/opt/epgstation/config
            - ./epgstation/data:/opt/epgstation/data
            - ./epgstation/thumbnail:/opt/epgstation/thumbnail
            - ./epgstation/logs:/opt/epgstation/logs
            - /mnt/data3/recorded:/opt/epgstation/recorded
            - ./epgstation/EPGS-to-Discord-v2:/opt/epgstation/EPGS-to-Discord-v2
            - socks:/var/run
        environment:
            TZ: "Asia/Tokyo"
        user: 0:0
        depends_on:
            - mirakc
            - mysql
        ports:
            - "8888:8888"
            - "8889:8889"
        #user: "1000:1000"
        restart: always
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    socks:
