---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    monitor: yudejp-monitor
scrape_configs:
  # - job_name: prometheus
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets:
  #         - prometheus:9090
  # - file_sd_configs:
  #     - files:
  #         - /etc/prometheus/node.yaml
  #   job_name: node
  - job_name: 'snmp_if_mib'
    static_configs:
      - targets:
        - 192.168.100.1  # ix2105
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116
  - job_name: snmp_nec_ix
    static_configs:
      - targets:
          - 192.168.100.1
    metrics_path: /snmp
    params:
      module:
        - nec_ix
    relabel_configs:
      - source_labels:
          - __address__
        target_label: __param_target
      - source_labels:
          - __param_target
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116