version: '3.1'

services:
  vpnclient:
    image: ghcr.io/yude/docker-softether-vpn-client:master
    privileged: true
    cap_add:
      - NET_ADMIN
    env_file:
      - ./.env
    restart: always

  pleroma:
    image: git.pleroma.social:5050/pleroma/pleroma:latest
    labels:
      - "org.label-schema.group=pleroma"
    restart: always
    env_file: ./environments/pleroma/pleroma.env
    depends_on:
      - pleroma-db
    volumes:
      - ./volumes/pleroma/config.exs:/var/lib/pleroma/config.exs
      - ./volumes/pleroma/uploads:/var/lib/pleroma/uploads
    cap_add:
      - NET_ADMIN
    depends_on:
      - vpnclient
    network_mode: "service:vpnclient"

  pleroma-db:
    image: postgres:12.1-alpine
    labels:
      - "com.centurylinklabs.watchtower.enable=False"
      - "org.label-schema.group=pleroma"
    restart: always
    env_file: ./environments/pleroma-db/postgres.env
    volumes:
      - ./volumes/pleroma-db/pgdata:/var/lib/postgresql/data
      - ./volumes/pleroma-db/pginit:/docker-entrypoint-initdb.d
    cap_add:
      - NET_ADMIN
    depends_on:
      - vpnclient
    network_mode: "service:vpnclient"
