version: '3.9'
services:
  h2o:
    image: lkwg82/h2o-http2-server:v2.2.6
    restart: unless-stopped
    working_dir: /etc/h2o
    volumes:
      - type: bind
        source: "./h2o.conf"
        target: "/etc/h2o/h2o.conf"
      - type: bind
        source: "./html"
        target: "/var/www/html"
    networks:
      - h5ai_default
      - gitea_default
      - nextcloud_default
      - overleaf_default
      - grafana_default
      - prometheus_default
      - minecraft_default
      - internal
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    user: root
    restart: unless-stopped
    command: tunnel --url http://h2o:8080 --no-chunked-encoding run proxy01
    volumes:
      - '$HOME/.cloudflared:/root/.cloudflared'
    depends_on:
      - h2o
    networks:
      - internal

networks:
  internal:
  h5ai_default:
    external: true
  gitea_default:
    external: true
  nextcloud_default:
    external: true
  overleaf_default:
    external: true
  grafana_default:
    external: true
  prometheus_default:
    external: true
  minecraft_default:
    external: true
