version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
#    devices:
#      - /dev/dri:/dev/dri
    volumes:
      - ./config:/config
      - cache:/cache
      - /store1/dtv:/media-dtv
      - /store3/video/yt_dl:/media-video-yt_dl
      - /store3/video/yt_limited:/media-video-yt_limited
      - /store3/nsfw/iwara:/media-nsfw-iwara
      - /store3/nsfw/asmr/DLsite:/media-nsfw-asmr
      - /store3/music:/media-music
    restart: always

volumes:
  cache:
