version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
#    devices:
#      - /dev/dri:/dev/dri
    volumes:
      - ./config:/config
      - cache:/cache
      - /store1/Documents/NSFW:/media-nsfw
      - /store1/dtv:/media-dtv
      - /store2/recorded:/media-recorded
      - /store1/Documents/Syncthing/Music:/media-music
    restart: "unless-stopped"

volumes:
  cache:
