version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - ./config:/config
      - cache:/cache
      - /mnt/data4/Documents/NSFW:/media-nsfw
      - /mnt/data4/dtv:/media-dtv
      - /mnt/data4/Documents/Syncthing/Music:/media-music
    restart: "unless-stopped"

volumes:
  cache:
