version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    volumes:
      - ./config:/config
      - cache:/cache
      - /mnt/data4/Documents/NSFW:/media-nsfw
      - /mnt/data1/dtv:/media-dtv
    restart: "unless-stopped"

volumes:
  cache: