version: "2.1"
services:
  jellyfin:
#    image: ghcr.io/linuxserver/jellyfin
    image: yude/jellyfin
    container_name: jellyfin
    deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [compute, utility, video]
    devices:
      - '/dev/dri:/dev/dri'
    environment:
      - PUID=1000 
      - PGID=1000
      - TZ=Asia/Tokyo
    volumes:
      - /home/yude/docker-compose/jellyfin/config:/config
      - /mnt/data1/dtv:/data/encoded
      - /mnt/data1/Music:/data/music
      - /mnt/data5/Documents/nsfw/iwara:/data/iwara
      - /mnt/data4/recorded:/data/recorded
    network_mode: host
    restart: unless-stopped
