services:
  portainer:
    image: portainer/portainer:latest
    ports:
      - 2002:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped
