version: "3"

services:
  softether:
    hostname: softether
    # image: ghcr.io/yude/docker-softether-vpn-client:master
    build:
      context: softether
      dockerfile: ./Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./softether/interfaces:/etc/network/interfaces
      - ./softether/supervisord.conf:/etc/supervisord.conf
    env_file:
      - softether/.env
    restart: always

  caddy:
    image: caddy
    restart: always
    environment:
      - TZ=Asia/Tokyo
    network_mode: "service:softether"
    depends_on:
      - softether
    volumes:
      - ./caddy/html:/usr/share/caddy
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile

  nichijid-rs:
    image: ghcr.io/yude/nichijid-rs:latest
    restart: always
    environment:
      - TZ=Asia/Tokyo
    network_mode: "service:softether"
    depends_on:
      - softether

  freepbx:
    image: tiredofit/freepbx:latest
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - ENABLE_FAIL2BAN=FALSE
      - HTTP_PORT=4080
      - HTTPS_PORT=40443
    network_mode: "service:softether"
    depends_on:
      - softether
    volumes:
      - ./freepbx/data:/data
