version: "3"

services:
  vpnclient:
    image: ghcr.io/yude/docker-softether-vpn-client:master
    hostname: yudesrv
    container_name: hvcan-vpn
    privileged: true
    cap_add:
      - NET_ADMIN
    env_file:
      - ./.env
    restart: always

  samba:
    image: servercontainers/samba
    container_name: hvcan-samba
    volumes:
      - /mnt/data3/share:/shares/share
    tty: yes
    restart: always
    cap_add:
      - NET_ADMIN
    depends_on:
      - vpnclient
    env_file:
      - .env
    network_mode: "service:vpnclient"
  
  nginx:
    image: nginx
    container_name: hvcan-nginx
    tty: yes
    restart: always
    cap_add:
      - NET_ADMIN
    depends_on:
      - vpnclient
    network_mode: "service:vpnclient"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./nginx/html:/var/www/html
  