version: "3"

services:
  vpnclient:
    image: ghcr.io/yude/docker-softether-vpn-client:master
    hostname: yudesrv
    container_name: hvcan-vpn
    privileged: true
    dns:
      - 8.8.8.8
      - 20.0.0.1
    cap_add:
      - NET_ADMIN
    env_file:
      - ./.env
    restart: always
    # important: this container owns the network stack 
    #            so expose guacamole ports here
    ports:
      - "5555:5555"

  samba:
    image: vimagick/samba
    volumes:
      - ./samba/smb.conf:/etc/samba/smb.conf
      - /mnt/data3/share:/share
    tty: yes
    restart: always
    cap_add:
      - NET_ADMIN
    depends_on:
      - vpnclient
    # use network stack of vpnclient to gain access to
    # the VPN network
    network_mode: "service:vpnclient"
  
  nginx:
    image: nginx
    tty: yes
    restart: always
    cap_add:
      - NET_ADMIN
    depends_on:
      - vpnclient
    network_mode: "service:vpnclient"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ./nginx/html:/var/www/html
